version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_cont
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: cliente_admin
      MYSQL_USER: sys_admin
      MYSQL_PASSWORD: cl1ntee
      MYSQL_ROOT_PASSWORD: root_cl1ntes
    volumes:
      - ./dataCreate/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:81
